const LANG={
 en:{cat_img:'Image models',cat_vid:'Video models',cat_chat:'Chat & Vision',mode_img:'Image Generation',mode_vid:'Video Generation',mode_chat:'Chat / Vision',placeholder_img:'Describe an image…',placeholder_vid:'Describe a video…',placeholder_chat:'Message or upload an image…',welcome:'Choose a model.<br>Image, Video, or Chat.',attached:'Image attached',drawing:'Generating image…',video:'Generating video…',thinking:'Thinking…',download:'Download',gallery:'My Gallery',empty:'No media yet.',error:'Request failed. Check the server environment variable or account balance.',next:'AR',land:'Generate professional media using modern AI technologies',support:'SITE SUPPORTS',chat:'AI Chat',vid:'AI Video',img:'AI Images',enter:'Enter App'},
 ar:{cat_img:'نماذج الصور',cat_vid:'نماذج الفيديو',cat_chat:'نماذج الشات والرؤية',mode_img:'توليد الصور',mode_vid:'توليد الفيديو',mode_chat:'شات / تحليل صور',placeholder_img:'اكتب وصف الصورة…',placeholder_vid:'اكتب وصف الفيديو…',placeholder_chat:'اكتب رسالة أو ارفع صورة…',welcome:'اختر النموذج المناسب.<br>صور أو فيديو أو شات.',attached:'صورة مرفقة',drawing:'جاري توليد الصورة…',video:'جاري توليد الفيديو…',thinking:'جاري التفكير…',download:'تحميل',gallery:'معرضي',empty:'لا توجد وسائط حتى الآن.',error:'فشل الطلب. تحقق من متغير البيئة أو الرصيد.',next:'EN',land:'أنشئ صورًا وفيديوهات احترافية باستخدام تقنيات الذكاء الاصطناعي',support:'الموقع يدعم',chat:'شات ذكي',vid:'فيديو ذكي',img:'صور ذكية',enter:'دخول التطبيق'}
};
const FALLBACK_MODELS=[
{id:'flux',name:'Flux',type:'image',description:'Fast image generation',inputModalities:['text']},
{id:'openai',name:'OpenAI',type:'chat',description:'Chat and vision',inputModalities:['text','image']},
{id:'gemini',name:'Gemini',type:'chat',description:'Chat and vision',inputModalities:['text','image']},
{id:'claude',name:'Claude',type:'chat',description:'General chat model',inputModalities:['text','image']},
{id:'mistral',name:'Mistral',type:'chat',description:'Fast general chat',inputModalities:['text']},
{id:'deepseek',name:'DeepSeek',type:'chat',description:'Reasoning and coding',inputModalities:['text']}
];
const ASPECTS={'1:1':{w:1024,h:1024},'16:9':{w:1280,h:720},'9:16':{w:720,h:1280},'4:3':{w:1024,h:768},'3:4':{w:768,h:1024}};
const $=id=>document.getElementById(id);
let models=[],currentModel=null,currentLang='en',currentAspect='1:1',currentImageBase64=null,isGenerating=false;

function escapeHtml(value){return String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function scrollBottom(){$('chatContainer').scrollTop=$('chatContainer').scrollHeight;}
function updateText(){const t=LANG[currentLang];$('langBtn').textContent=$('langBtnLanding').textContent=t.next;$('txtWelcome').innerHTML=t.welcome;$('previewInfo').textContent=t.attached;$('galleryTitle').textContent=t.gallery;$('landDesc').textContent=t.land;$('landSupport').textContent=t.support;$('featText').textContent=t.chat;$('featVideo').textContent=t.vid;$('featImg').textContent=t.img;$('btnLogin').textContent=t.enter;}
function toggleLanguage(){currentLang=currentLang==='en'?'ar':'en';document.documentElement.lang=currentLang;document.documentElement.dir=currentLang==='ar'?'rtl':'ltr';document.body.classList.toggle('lang-ar',currentLang==='ar');updateText();renderModelMenu();if(currentModel)selectModel(currentModel.id,currentModel.type);}
function renderAspects(){$('aspectMenu').innerHTML=Object.keys(ASPECTS).map(r=>`<button class="aspect-option ${r===currentAspect?'selected':''}" data-ratio="${r}">${r}</button>`).join('');$('aspectMenu').querySelectorAll('button').forEach(b=>b.onclick=()=>{currentAspect=b.dataset.ratio;$('aspectLabel').textContent=currentAspect;$('aspectMenu').style.display='none';renderAspects();});}
function renderModelMenu(){const t=LANG[currentLang],menu=$('modelMenu');menu.innerHTML='';[['image',t.cat_img],['video',t.cat_vid],['chat',t.cat_chat]].forEach(([type,title])=>{const list=models.filter(m=>m.type===type);if(!list.length)return;menu.insertAdjacentHTML('beforeend',`<div class="model-category">${escapeHtml(title)}</div>`);list.forEach(m=>{const button=document.createElement('button');button.className=`model-option plain-button ${currentModel?.id===m.id&&currentModel?.type===m.type?'active':''}`;button.innerHTML=`<span><span class="model-name">${escapeHtml(m.name)}</span><span class="model-desc">${escapeHtml(m.description)}</span></span><span>✓</span>`;button.onclick=()=>selectModel(m.id,m.type);menu.appendChild(button);});});}
function selectModel(id,type){currentModel=models.find(m=>m.id===id&&m.type===type)||models.find(m=>m.id===id);if(!currentModel)return;localStorage.setItem('nanoSelectedModel',JSON.stringify({id:currentModel.id,type:currentModel.type}));$('headerModelName').textContent=currentModel.name;document.body.classList.remove('mode-chat','mode-video');const t=LANG[currentLang];$('aspectBtn').style.display=currentModel.type==='chat'?'none':'block';if(currentModel.type==='chat'){document.body.classList.add('mode-chat');$('modelModeText').textContent=t.mode_chat;$('promptInput').placeholder=t.placeholder_chat;$('emptyLogo').textContent='👁️';$('sendBtn').style.background='var(--blue)';}else if(currentModel.type==='video'){document.body.classList.add('mode-video');$('modelModeText').textContent=t.mode_vid;$('promptInput').placeholder=t.placeholder_vid;$('emptyLogo').textContent='🎬';$('sendBtn').style.background='var(--red)';}else{$('modelModeText').textContent=t.mode_img;$('promptInput').placeholder=t.placeholder_img;$('emptyLogo').textContent='✨';$('sendBtn').style.background='var(--accent)';}const supportsImage=currentModel.type==='chat'||currentModel.inputModalities?.includes('image');$('attachBtn').style.display=supportsImage?'grid':'none';if(!supportsImage)clearImage();$('modelMenu').style.display='none';renderModelMenu();}
function renderUser(text,img){$('emptyState').style.display='none';const d=document.createElement('div');d.className='message user';d.innerHTML=`<div class="msg-bubble">${img?`<img class="user-img-display" src="${img}" alt="">`:''}${text?`<div>${escapeHtml(text)}</div>`:''}</div>`;$('chatContainer').appendChild(d);scrollBottom();}
function renderLoader(text){const d=document.createElement('div');d.className='message bot';d.id=`load-${Date.now()}`;d.innerHTML=`<div class="typing">${escapeHtml(text)}</div>`;$('chatContainer').appendChild(d);scrollBottom();return d.id;}
function renderText(text){const d=document.createElement('div');d.className='message bot';d.innerHTML=`<div class="msg-bubble">${window.marked?marked.parse(text):escapeHtml(text)}</div>`;$('chatContainer').appendChild(d);scrollBottom();}
function renderMedia(blob,isVideo){const url=URL.createObjectURL(blob),d=document.createElement('div');d.className='message bot';d.innerHTML=`<div class="msg-bubble">${isVideo?`<video class="msg-media" src="${url}" autoplay loop controls playsinline></video>`:`<img class="msg-media" src="${url}" alt="Generated image">`}<div class="media-actions"><button class="download-btn">${LANG[currentLang].download}</button></div></div>`;d.querySelector('button').onclick=()=>downloadBlob(blob,isVideo?'mp4':'png');$('chatContainer').appendChild(d);gallery.unshift({blob,url,type:isVideo?'video':'image'});scrollBottom();}
function downloadBlob(blob,ext){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ai-${Date.now()}.${ext}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function clearImage(){currentImageBase64=null;$('fileInput').value='';$('previewContainer').style.display='none';}
async function readJsonResponse(response){const raw=await response.text();if(!raw)return {};try{return JSON.parse(raw);}catch{throw new Error(raw.slice(0,500)||`Server returned an invalid response (${response.status}).`);}}
async function callChat(model,messages){const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model,messages})});const d=await readJsonResponse(r);if(!r.ok)throw new Error(d.error||`Chat request failed (${r.status})`);return d.choices?.[0]?.message?.content||'';}
async function createPromptFromImage(instruction){return callChat('openai',[{role:'user',content:[{type:'text',text:`Analyze this image and create a detailed generation prompt that follows this instruction: ${instruction||'recreate the image'}. Return only the prompt.`},{type:'image_url',image_url:{url:currentImageBase64}}]}]);}
async function generateMedia(prompt){const dim=ASPECTS[currentAspect],r=await fetch('/api/media',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:currentModel.id,prompt,width:dim.w,height:dim.h,seed:Math.floor(Math.random()*1e9)})});if(!r.ok){const d=await readJsonResponse(r);throw new Error(d.error||`Media request failed (${r.status})`);}const blob=await r.blob(),type=r.headers.get('content-type')||blob.type;return {blob,isVideo:type.startsWith('video/')||currentModel.type==='video'};}
async function sendMessage(){const text=$('promptInput').value.trim();if((!text&&!currentImageBase64)||!currentModel||isGenerating)return;isGenerating=true;$('sendBtn').disabled=true;const image=currentImageBase64;renderUser(text,image);$('promptInput').value='';const loader=renderLoader(currentModel.type==='chat'?LANG[currentLang].thinking:currentModel.type==='video'?LANG[currentLang].video:LANG[currentLang].drawing);try{if(currentModel.type==='chat'){const content=image?[{type:'text',text:text||'Describe this image.'},{type:'image_url',image_url:{url:image}}]:text;const answer=await callChat(currentModel.id,[{role:'system',content:currentLang==='ar'?'أجب بالعربية واستخدم Markdown.':'Reply in English using Markdown.'},{role:'user',content}]);$(loader)?.remove();renderText(answer);}else{const finalPrompt=image?await createPromptFromImage(text):text;const result=await generateMedia(finalPrompt);$(loader)?.remove();renderMedia(result.blob,result.isVideo);}clearImage();}catch(error){console.error(error);$(loader)?.remove();renderText(`${LANG[currentLang].error}\n\n${error.message}`);}finally{isGenerating=false;$('sendBtn').disabled=false;}}
const gallery=[];
function renderGallery(){const grid=$('galleryGrid');grid.innerHTML='';if(!gallery.length){grid.innerHTML=`<div class="empty-gallery-msg">${LANG[currentLang].empty}</div>`;return;}gallery.forEach((item,index)=>{const d=document.createElement('div');d.className='gallery-item';d.innerHTML=item.type==='video'?`<video src="${item.url}" controls></video><button>⬇</button>`:`<img src="${item.url}" alt=""><button>⬇</button>`;d.querySelector('button').onclick=()=>downloadBlob(item.blob,item.type==='video'?'mp4':'png');grid.appendChild(d);});}
async function loadModels(){const r=await fetch('/api/models',{cache:'no-store'});const data=await readJsonResponse(r);if(!r.ok)throw new Error(data.error||`Could not load models (${r.status})`);models=Array.isArray(data.models)&&data.models.length?data.models:FALLBACK_MODELS;}

$('btnLogin').onclick=()=>{$('landingPage').style.opacity='0';$('landingPage').style.visibility='hidden';};
$('langBtn').onclick=$('langBtnLanding').onclick=toggleLanguage;
$('modelMenuButton').onclick=()=>{$('modelMenu').style.display=$('modelMenu').style.display==='flex'?'none':'flex';};
$('aspectBtn').onclick=()=>{$('aspectMenu').style.display=$('aspectMenu').style.display==='flex'?'none':'flex';};
$('attachBtn').onclick=()=>$('fileInput').click();
$('fileInput').onchange=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=event=>{currentImageBase64=event.target.result;$('previewThumb').src=currentImageBase64;$('previewContainer').style.display='flex';};reader.readAsDataURL(file);};
$('removeImageButton').onclick=clearImage;
$('sendBtn').onclick=sendMessage;
$('promptInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMessage();}});
$('galleryButton').onclick=()=>{$('galleryModal').style.display='flex';renderGallery();};
$('galleryClose').onclick=()=>{$('galleryModal').style.display='none';};
document.addEventListener('click',e=>{if(!$('aspectMenu').contains(e.target)&&!$('aspectBtn').contains(e.target))$('aspectMenu').style.display='none';});
window.addEventListener('load',async()=>{updateText();renderAspects();$('sendBtn').disabled=true;try{await loadModels();}catch(error){console.error(error);models=FALLBACK_MODELS;}let saved={};try{saved=JSON.parse(localStorage.getItem('nanoSelectedModel')||'{}');}catch{}renderModelMenu();const selected=models.find(m=>m.id===saved.id&&m.type===saved.type)||models.find(m=>m.id==='flux')||models[0];if(selected)selectModel(selected.id,selected.type);$('sendBtn').disabled=false;});
