import { createClient } from '@supabase/supabase-js';
import { SignJWT, jwtVerify } from 'jose';

const supabaseUrl=process.env.SUPABASE_URL;
const serviceRoleKey=process.env.SUPABASE_SERVICE_ROLE_KEY;
const jwtSecret=process.env.APP_JWT_SECRET;
const PI_BASE=(process.env.PI_API_BASE_URL||'https://api.minepi.com').replace(/\/$/,'');
const MEDIA_BUCKET='app-media';

export function requireEnv(){const m=[];if(!supabaseUrl)m.push('SUPABASE_URL');if(!serviceRoleKey)m.push('SUPABASE_SERVICE_ROLE_KEY');if(!jwtSecret||jwtSecret.length<32)m.push('APP_JWT_SECRET');if(m.length)throw new Error(`Missing environment variables: ${m.join(', ')}`)}
export function db(){requireEnv();return createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}})}
export function json(res,status,body){res.status(status).setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');return res.end(JSON.stringify(body))}
export function allowMethods(req,res,methods){if(methods.includes(req.method))return true;res.setHeader('Allow',methods.join(', '));json(res,405,{error:'Method not allowed'});return false}
export async function signAppToken(user){requireEnv();return new SignJWT({username:user.username,pi_uid:user.pi_uid}).setProtectedHeader({alg:'HS256'}).setSubject(user.id).setIssuedAt().setExpirationTime('24h').sign(new TextEncoder().encode(jwtSecret))}
export async function requireUser(req){requireEnv();const auth=req.headers.authorization||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)throw new Error('UNAUTHORIZED');const {payload}=await jwtVerify(token,new TextEncoder().encode(jwtSecret));if(!payload.sub)throw new Error('UNAUTHORIZED');const {data:user,error}=await db().from('users').select('id,username,pi_uid,role').eq('id',payload.sub).maybeSingle();if(error||!user)throw new Error('UNAUTHORIZED');return user}
export function requireAdmin(user){if(!['admin','moderator'].includes(user.role))throw new Error('FORBIDDEN')}
export function cleanText(v,max=500){return String(v??'').trim().slice(0,max)}
export function safeUrl(v){const u=new URL(String(v));if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw new Error('INVALID_URL');return u.toString()}
export function safeEmail(v){const value=cleanText(v,160).toLowerCase();if(!value)return '';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new Error('INVALID_EMAIL');return value}
export function trustedMediaUrl(v,ownerId){const value=safeUrl(v);const url=new URL(value),base=new URL(supabaseUrl);const marker=`/storage/v1/object/public/${MEDIA_BUCKET}/`;if(url.origin!==base.origin||!url.pathname.startsWith(marker))throw new Error('INVALID_MEDIA_URL');const path=decodeURIComponent(url.pathname.slice(marker.length));if(!path||path.includes('..')||!path.startsWith(`${ownerId}/`))throw new Error('INVALID_MEDIA_URL');return value}
export function getClientIp(req){return cleanText((req.headers['x-forwarded-for']||'').split(',')[0]||req.socket?.remoteAddress||'unknown',100)}
export async function rateLimit(req,{key,limit,windowSeconds,userId=null}){try{const {data,error}=await db().rpc('consume_api_rate_limit',{p_key:`${key}:${userId||getClientIp(req)}`,p_limit:limit,p_window_seconds:windowSeconds});if(error)throw error;if(data===false)throw new Error('RATE_LIMITED')}catch(error){if(error.message==='RATE_LIMITED')throw error;console.error('Rate limit check unavailable:',error.message)}}
export async function piRequest(path,{method='GET',body}={}){const key=process.env.PI_SECRET_KEY;if(!key)throw new Error('PI_SECRET_KEY is not configured');const response=await fetch(`${PI_BASE}${path}`,{method,headers:{Authorization:`Key ${key}`,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json().catch(()=>null);if(!response.ok){const error=new Error('PI_API_ERROR');error.status=response.status;error.data=data;throw error}return data}
export function assertPiPayment(payment,{paymentId,userUid,amount,purpose,appId}){if(!payment||String(payment.identifier)!==String(paymentId))throw new Error('PAYMENT_MISMATCH');if(String(payment.user_uid)!==String(userUid))throw new Error('PAYMENT_MISMATCH');if(String(payment.direction||'').toLowerCase()!=='user_to_app')throw new Error('PAYMENT_MISMATCH');if(Math.abs(Number(payment.amount)-Number(amount))>0.000001)throw new Error('PAYMENT_MISMATCH');if(String(payment.metadata?.purpose||'')!==purpose)throw new Error('PAYMENT_MISMATCH');if(appId!=null&&String(payment.metadata?.appId||'')!==String(appId))throw new Error('PAYMENT_MISMATCH');if(payment.status?.cancelled||payment.status?.user_cancelled)throw new Error('PAYMENT_CANCELLED');return payment}
export function handleError(error,res,fallback='Server error'){console.error(error);if(error.message==='UNAUTHORIZED')return json(res,401,{error:'Sign in with Pi first'});if(error.message==='FORBIDDEN')return json(res,403,{error:'Admin access required'});if(error.message==='INVALID_URL')return json(res,400,{error:'Invalid URL'});if(error.message==='INVALID_MEDIA_URL')return json(res,400,{error:'Logo and screenshots must be uploaded through AppHub'});if(error.message==='INVALID_EMAIL')return json(res,400,{error:'Invalid contact email'});if(error.message==='RATE_LIMITED')return json(res,429,{error:'Too many requests. Please wait and try again.'});if(error.message==='PAYMENT_MISMATCH')return json(res,400,{error:'Payment details do not match this action'});if(error.message==='PAYMENT_CANCELLED')return json(res,400,{error:'Payment was cancelled'});if(error.message==='PI_API_ERROR')return json(res,error.status||502,{error:error.data?.error||error.data||'Pi API request failed'});return json(res,500,{error:fallback})}
